baseURL: "https://spaudel.github.io" 
title: Shreyasha Paudel
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
      - name: About Me 
        url: about/
      - name: Publications
        url: papers/
      - name: Projects
        url: projects/
        # - name: Books
        #   url: books/
        #   weight: 5 
        # - name: Papers
        #   url: papers/
        #   weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This is the personal website of Shreyasha Paudel."
    author: Shreyasha Paudel
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "November 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["About Me", "Projects", "Publications"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shreyasha Paudel
          subtitle: "I am a Ph.D. student at the University of Toronto in the Department of Computer Science. I am part of the Toronto Climate Observatory where I do interdisciplinary place-based research on climate and disaster data under the supervision of Professor Robert Soden. My research interests lie at the intersection of Human Computer Interaction, Critical Data Studies, and Feminist and Decolonial STS and I use historicist methods, ethnography, and participatory design methods to pursue them."
          imageUrl: "shrey_pdl.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about/
            - name: Publications
              url: papers/
            - name: Projects
              url: projects/
            #- name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Shreyasha_Paudel_CV_UToronto.pdf
        
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=AbniDkgAAAAJ&view_op=list_works&sortby=pubdate
        - name: LinkedIn
          url: https://www.linkedin.com/in/shreyashapaudel
        - name: Email
          url: mailto:shreyasha.paudel@mail.utoronto.ca
        # - name: GitHub
        #   url: https://github.com/pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shreyasha Paudel"
      icon: picture.jpeg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
